### ISSUE TITLE
Remove overall column and have Study labels horisontally

### ISSUE THREAD

**Issue by henda52** [mcguinlu/robvis#132]
Thanks for a great tool!

I'm making a traffic light summary of a ROB tool that is not in your templates. It has 10 different ROB estimates and no overall judgment.  There are 49 studies.

As I understand it, I have to use the tool = "ROB1" setting because it doesn't fit with the other templates. However, for this template, the overall= FALSE setting is not available (I get unused argument when I try to use that). My workaround is to create an overall column in the dataset and ignore it in the produced figure (or crop it in a software).

Is there a way to remove the overall column in this case? 

Another problem is that the Study labels are written vertically and the does not fit within the small grey box so they are unreadable. Is there a way to make the Study label box larger so that the name of the study is visible?

Here is a minimal reproducible example

df <- dplyr::bind_rows(data_rob1, data_rob1, data_rob1, data_rob1, data_rob1) 
df$Study <- paste0("Study ", seq.int(from = 1, to =45))
df %>%
  robvis::rob_traffic_light(tool = "ROB1", colour = "cochrane", psize = 5)

**Comment by mcguinlu** [comment]
Hi @henda52 - thanks for your message.

For the vertical study label issue, see here: https://github.com/mcguinlu/robvis/issues/81

Unfortunately, I am in the last couple of weeks of my PhD and so won't have a chance to look at the overall column issue before Christmas. There is a load of new functionality coming to `robvis` in the New Year though, so I'll add this to the list of things to address as part of that overhaul!

**Comment by henda52** [comment]
Thanks so much!
The update helped. Looking forward to the new version next year. 
Good luck with the Phd!

**Comment by Rmadillo** [comment]
Hi Luke! Thanks for an awesome tool!!! 

I have the same issue as @henda52 in that I don't have an overall column and wondering if you'd had a chance to work on this aspect of it for ROB1/Generic, i.e., an `overall = F`. I can see it works in the webapp, but when you uncheck Overall column in the webapp, the legend and caption overwrite each other when you download the image.

**Comment by mcguinlu** [comment]
Hey @Rmadillo @henda52 - just a heads up that the development version of `robvis` now supports this functionality (also discussed in #123). 

Install/update to the new development version by running:

```
install.packages("devtools")
devtools::install_github("mcguinlu/robvis")
```

As an illustration, the following code:

```
robvis::rob_traffic_light(
  data_rob1[1:8],
  tool = "Generic",
  overall = FALSE
)
```
will now produce the image below, with the expected behaviour for `overall = FALSE`:

![Rplot01](https://github.com/mcguinlu/robvis/assets/41202585/81a269ce-d5bd-4e43-a459-b3a40e639f36)

**Comment by Rmadillo** [comment]
That’s wonderful, thanks so much!

On Jun 7, 2023, at 11:55, Luke McGuinness ***@***.***> wrote:

﻿

Hey @Rmadillo<https://github.com/Rmadillo> @henda52<https://github.com/henda52> - just a heads up that the development version of robvis now supports this functionality (also discussed in #123<https://github.com/mcguinlu/robvis/issues/123>).

Install/update to the new development version by running:

install.packages("devtools")
devtools::install_github("mcguinlu/robvis")


As an illustration, the following code:

robvis::rob_traffic_light(
  data_rob1[1:8],
  tool = "Generic",
  overall = FALSE
)


will now produce the image below, with the expected behaviour for overall = FALSE:

[Rplot01]<https://user-images.githubusercontent.com/41202585/244167589-81a269ce-d5bd-4e43-a459-b3a40e639f36.png>

**Comment by henda52** [comment]
Thank you!
