### ISSUE TITLE
Cannot produce traffic light plot with .csv file

### ISSUE THREAD

**Issue by daryl-hodge** [mcguinlu/robvis#137]
Uploaded a .csv file, the data review looked fine. The summary plot works, but the traffic light had a red error message reading "An error has occurred. Please double-check your [sic] that your selected tool matches the data your uploaded (common problem). If you believe you have found a bug, please contact me! The error is:"  (no error was stated).

I got around this by uploading a .xlsx file, which worked no problem. The data appear to be the same in both files.

Steps to reproduce the behaviour:
1. Specify Generic
2. Upload .csv file
3. Generate plots

**Comment by mcguinlu** [comment]
Hey @daryl-hodge, thanks for opening this.

Unfortunately I wasn't able to recreate the bug on my end - using a CSV instead of an XLSX did not cause any issues.

My process was to:
1) Download the ROB2 example XLSX file from the `robvis` website
2) Save the XLSX to CSV format
3) Upload the CSV to `robvis`
4) Generate the plots, as normal

Could you attached the CSV you are trying to upload here, so that I can check if it is something particular to your data that is causing the issue?

**Comment by daryl-hodge** [comment]
Hi there,

Obviously it has been a few months now, so I am not entirely sure of which .csv file it was I was trying to upload. I’ve attached the file that it probably was!

Best wishes,

Daryl

Dr Daryl Hodge (they/them)
Pharmacology & Therapeutics
Content Manager - HEP Drug Interactions<https://www.hepatology-druginteractions.org/>
Editorial Assistant – HIV<https://www.hiv-druginteractions.org/> & COVID-19<https://www.covid19-druginteractions.org/> Drug Interactions

***@***.***
I support colleagues undertaking the UCU Rising Marking and Assessment boycott: find out more here<https://ulivucunews.org.uk/ucu-rising/>.
