### ISSUE TITLE
QUADAS-2 issue

### ISSUE THREAD

**Issue by cychou13** [mcguinlu/robvis#138]
Hi
In the QUADAS-2, Risk of bias (D1-D4) and applicability judgments (D1-D3)
with the title "Risk of bias" and "applicability judgments"
However, the QUADAS-2 tool only allows D1-D4 and Overall.
Is there any to fix this?
Regards

**Comment by mcguinlu** [comment]
Hey @cychou13,

This is intended behaviour, as `robvis` is primarily meant to deal with risk of bias assessment, rather than applicability assessments.

However, a recent update (via #143) allows users to specify the domain shortcodes, so it is now possible to include both on a single plot:

```
# Create example dataset
df <- cbind(data_quadas[, 1:5], data_quadas[3:5])

# Rename columns
colnames(df) <- c(

  "Study",
  "Patient Selection (Bias)",
  "Index test (Bias)",
  "Reference standard (Bias)",
  "Flow and timing (Bias)",
  "Patient Selection (Applicability)",
  "Index test (Applicability)",
  "Reference standard (Applicability)"
)

# Create traffic light
rob_traffic_light(
  df,
  "Generic",
  overall = FALSE,
  domain_shortcodes = c("R1", "R2", "R3", "R4", "A1", "A2", "A3"),
  x_title = "Bias/Applicability Domains"
) 
```

The code above will create the following image:

![Rplot01](https://github.com/mcguinlu/robvis/assets/41202585/62dd2267-4deb-4f75-9013-bc9447219356)
