### ISSUE TITLE
ROBINS-I plots can't deal with 'NI' (No information)

### ISSUE THREAD

**Issue by befriendabacterium** [mcguinlu/robvis#149]
**Describe the bug**
The ROBINS-I tool allows for the Domain or Overall RoB judgement to be 'No information' (coded as NI) where there is no information to base risk of bias judgement on.

**To Reproduce**
```
# load example data
data <- data_robins
data$Study <- paste("Study",seq(1,nrow(data)))
#coerce to character to simulate reading ina raw .csv file
data<-as.data.frame(apply(data,2,as.character))
#replace one judgement with 'NI
data$D7[1]<-'NI'
# Plot 
rob_traffic_light(data, tool = "ROBINS-I", psize = 10)

```
Doing this screws up the 'Serious' judgements, such that they are plotted as grey (i.e. no colour) like the 'NI' ones and not included in the legend

**Expected behavior**
'Serious' should be plotted as cherry red, and NI should be plotted as grey. Both should be included in Judgement legend.

**Screenshots**
![image](https://github.com/mcguinlu/robvis/assets/42059798/35b30300-43ba-4718-b0ff-97b1dd09bdf1)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Interface: RStudio/R/robvis
 - Version: "Mountain Hydrangea" 2023.06.1 Build 524/4.3.1/CRAN version of robvis

**Additional context**
Ignore the other issues in the plot, i've flagged them elsewhere. Thanks for making this package, still a lot easier than doing myself!

**Comment by befriendabacterium** [comment]
Just to flag it, the Domain captions overlapping with the traffic lights (y axis displacement here seems to be related to this issue so once solved it should fix that too. But the x-axis displacement is a separate issue that needs to be dealt with otherwise https://github.com/mcguinlu/robvis/issues/148

**Comment by befriendabacterium** [comment]
FYI this issue also seems to displace the Domains caption of the y axis so it overlaps with traffic lights (see screenshot)

**Comment by mcguinlu** [comment]
Hi @befriendabacterium,

Thanks for raising this issue and for your patience while I got to it!

Based on the fact you are using `data_robins` vs `data_robins_i`, it seems likely you are using the CRAN version of `robvis`, which does not support "No information" as a judgement in `rob_traffic_light()`. 

If you use the latest development version from GitHub (via `devtools::install_github("mcguinlu/robvis")`), "No information" will be supported.

In fact, the example data for ROBINS-I included with the development version of the package already contains some "No information" judgements:

```
head(data_robins_i, 2)
```

|Study   |D1       |D2             |D3       |D4  |D5       |D6       |D7       |Overall  |
|:-------|:--------|:--------------|:--------|:---|:--------|:--------|:--------|:--------|
|Study 1 |Moderate |Critical       |Low      |Low |Moderate |Moderate |Moderate |Critical |
|Study 2 |Moderate |No information |Moderate |Low |Low      |Low      |Moderate |Moderate |

<br>

<br>

Passing this example dataset to the `rob_traffic_light()` function gives the following:

```
rob_traffic_light(data_robins_i, "ROBINS-I")
```
![rob_figure](https://github.com/mcguinlu/robvis/assets/41202585/fb2d2818-d20f-4bcc-a1f6-b62ced155163)

<br>

<br>

The CRAN version of `robvis` is now quite out of date, so in general you are better off using the dev version, as it contains fixes for a lot of issues that have cropped up in the years since `robvis` was first released. It's been on my radar for a while to release a new version, but I haven't quite found the time to dedicate to it yet!

**Comment by befriendabacterium** [comment]
Hi Luke,

Thanks for this and additional context re current CRAN version. Installed dev version and can confirm it fixes this issue with the correct inputs.

Thanks
Matt
