### ISSUE TITLE
Interested in a JOSS publication?

### ISSUE THREAD

**Issue by seabbs** [mcguinlu/robvis#62]
Hi Luke, 

Nice to meet you the other day!

This package looks  pretty neat - I was wondering whether you were thinking about getting it ready for a [JOSS](https://joss.theoj.org) submission? 

If so I would be happy to give it a once over (using their reviewing standards) - I think they are generally pretty good targets to aim for. Process is like this: https://github.com/openjournals/joss-reviews/issues/1260

Also very happy to give you a hand with anything  that might come up! 

Sam

**Comment by mcguinlu** [comment]
Hi @seabbs, 

Great to meet you too! 

The current plan is to initally submit it to the [Reseach Synthesis Methods](https://onlinelibrary.wiley.com/journal/17592887) call for papers on [data visualisation in evidence synthesis](https://onlinelibrary.wiley.com/pb-assets/Olivia%20Reed/JRSM%20Call%20for%20papers_Data%20Visualization%20Methods.pdf). We submitted an article proposal on `robvis` to this call in September, which was accepted, and are currently preparing a full article for submission this side of Christmas.

The only thing is that, while the RSM will publicize it to the group of users we want it to reach, they do not perform any peer-review of the package from a coding point of view.

Based on this, I don't know if you think there is scope to do both, as I think it would be worthwhile having someone other than me give it a good going through! There are some (/loads) of small issues that I know I need to deal with but just haven't got to, for example:

* Better (/any) testing - if you had any advice on how to test `ggplot`-object creating functions would be appreciated!
* Streamline the coding/functions (i.e. assigned the colours once within their own function, rather than seperately in each template)

Interested to hear what you think! 

Luke

**Comment by seabbs** [comment]
That plan makes a lot of sense and yes you can submit to both. 

The research methods paper becomes methods + use case and the JOSS paper reviews the actual code. I always find it a little odd when code isn't peer-reviewed when it is the actual output of the research. 

In terms of the things to do your correct about the tests (I would look at {vdiffr}). I would be happy to look through the package if your interested (I'm avoiding paper corrections :smile:)? Depending on what comes up I may be able to help make some changes or you may just need  to tweak the docs to be ready for JOSS (getting ready for CRAN + having tests is most of the battle).

**Comment by mcguinlu** [comment]
> The research methods paper becomes methods + use case and the JOSS paper reviews the actual code. 

Yes, that's exactly the plan.

>I always find it a little odd when code isn't peer-reviewed when it is the actual output of the research. 

I completely agree, but from what I've heard, code review is resource intense.

Re: running through the package, please fire away - always happy to help someone productively procrastinate! If you could flag things you find as issues, even if you are also working on fix via a PR, that would be great, just so I have an complete list.

Finally, I feel have to proactively apologise for the layout of some of the `ggplot` functions. I recently tried to use an automatic formatter to tidy up the code (I think it was the built in Rstudio one) which apparently doesn't handle ggplot code too well, and haven't got round to reformatting them properly.

Just to note that the intial version of `robvis` is currently working its way through an initial [CRAN submission cycle](https://cransays.itsalocke.com/articles/dashboard), following a few small issues and a resubmission - so hopefully that'll be another thing checked off the JOSS checklist soon! 

And finally, thanks @seabbs - great to have your interest/experience when working on this, as I know you almost certainly have a load of demands on your time!

**Comment by mcguinlu** [comment]
Hi @seabbs, 

I'm just doing a purge of issues on this repo, and as my capacity has become somewhat limit since this issue came up, I am going to close it.

The tool was published in RSM last Spring and we now have a few contributors providing features and patches to the codebase - 
 so I'm going to be cheeky, call this "community-review", and check this item off my to-do list 😁

Hope all is going well there!
