### ISSUE TITLE
traffic light plot study column appears as vertical instead of horizontal

### ISSUE THREAD

**Issue by ailengt** [mcguinlu/robvis#77]
The traffic light plot generated appears in vertical view instead of horizontal as pictured below. It is weird as I had generated it before and it was fine but it suddenly changed to a vertical view instead this time around. I have the latest packages installed and I can't seem to figure out how to troubleshoot it. Hope this issue can be resolved. Thank you. 

![image](https://user-images.githubusercontent.com/63007761/78158125-70c15180-7473-11ea-87de-2af2d935e25d.png)

**Comment by mcguinlu** [comment]
Hi @ailengt, 

Thanks for your message - this is a known issue, and it is due to changes in the way the `ggplot2` package orientates the labels of facet levels since V3.3.0 of that package.

If you install the development version via the code below, and make sure you have the most current version of `ggplot2`, it should work as expected:

```
install.packages("devtools")
devtools::install_github("mcguinlu/robvis")
```

Please let me know if that doesn't work. For reference, the fix should be add to the CRAN version of `robvis` in the coming weeks!

**Comment by ailengt** [comment]
Hi @mcguinlu 

Thank you for the prompt reply. The fix did the trick and resolved the problem. Thank you very much again!

**Comment by mcguinlu** [comment]
Excellent - glad it worked!
